# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('order_priority', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('label', models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Medium'), (3, 'Light')], default=2)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
