# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Medium'), (3, 'Light')], default=2, null=True),
        ),
    ]
