# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170927_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Medium'), (3, 'Light')], default=2),
        ),
    ]
